[[language]]
name = "astro"
scope = "source.astro"
injection-regex = "astro"
file-types = ["astro"]
language-servers = ["astro-ls"]
indent = { tab-width = 2, unit = "  "}

[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]

